### PR TITLE
Add optional annotations for zabbix-server service

### PR DESCRIPTION
**Pull request by plicon**
#### What this PR does / why we need it:
Add optional annotations for zabbix-service. Can be used for requesting a specific ip-pool from metallb. 
#### Which issue this PR fixes
* none, new feature

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by aeciopires — CHANGES_REQUESTED** [review]
Hello @plicon!

Thanks for your contributition!

Can you change version of chart to 1.1.1 in Chart.yaml file and run the command ``helm-docs``? 

Doc for install helm-docs: https://github.com/cetic/helm-zabbix/blob/master/docs/requirements.md#helm-docs

**Comment by plicon** [comment]
Hi @aeciopires, 

Just updated the version and ran helm-docs .. see commit … [4f62d80](https://github.com/cetic/helm-zabbix/pull/48/commits/4f62d80bd23395069f0c2c6b0840792a29234c39)

**Comment by aeciopires** [comment]
Great job @plicon!

What do you think about making this same change for the zabbix-agent, zabbix-web and zabbix-proxy services?

In this case, the changes would be in this same PR... so I merge and generate the version with those changes all at once.

**Comment by plicon** [comment]
@aeciopires  Sure and done! :)

**Review by aeciopires — APPROVED** [review]
Great job @plicon!

Thanks for your help.

**Pull request merged**
