### PR TITLE
add resource configuration

### PR DESCRIPTION
**Pull request by scoopex**
solves, https://github.com/cetic/helm-zabbix/issues/24

### CODE REVIEW

**Comment by scoopex** [comment]
Modified chart published at https://flip-corp.github.io/helm-zabbix

**Comment by aeciopires** [comment]
Hello @scoopex!

Can you resolve this conflict? I merged the PR 26 before... :-(

**Comment by scoopex** [comment]
Fixed :-)

**Comment by aeciopires** [comment]
Thank you so much @scoopex!

**Pull request merged**
